// Client-safe suspect card data
// This file contains minimal data for UI display - IDs must match suspects.ts

import { SuspectCardData } from "@/components/suspect-card";

export const suspectCards: SuspectCardData[] = [
  // Financial Crimes
  {
    id: "AX-7829",
    name: "Rajesh Kumar",
    age: 34,
    gender: "Male",
    city: "Mumbai",
    occupation: "Senior Accountant",
    employer: "TechCorp Solutions",
    priorCount: 1,
    currentCrime: "Embezzlement",
    caseAmount: "₹15,00,000",
    maxSentence: "7 years",
  },
  {
    id: "BK-4521",
    name: "Priya Sharma",
    age: 28,
    gender: "Female",
    city: "Delhi",
    occupation: "Bank Teller",
    employer: "National Bank of India",
    priorCount: 0,
    currentCrime: "Theft",
    caseAmount: "₹2,50,000",
    maxSentence: "3 years",
  },
  {
    id: "CM-9012",
    name: "Vikram Singh",
    age: 42,
    gender: "Male",
    city: "Jaipur",
    occupation: "Auto Dealer",
    employer: "Singh Motors",
    priorCount: 2,
    currentCrime: "Hit and Run",
    maxSentence: "10 years",
  },
  {
    id: "DL-3344",
    name: "Anil Kapoor",
    age: 55,
    gender: "Male",
    city: "Pune",
    occupation: "Government Clerk",
    employer: "Pune Municipal Corporation",
    priorCount: 0,
    currentCrime: "Bribery & Corruption",
    caseAmount: "₹25,00,000",
    maxSentence: "7 years",
  },
  {
    id: "EF-8877",
    name: "Kavita Deshmukh",
    age: 38,
    gender: "Female",
    city: "Nagpur",
    occupation: "Insurance Agent",
    employer: "BharatLife Insurance",
    priorCount: 0,
    currentCrime: "Insurance Fraud",
    caseAmount: "₹45,00,000",
    maxSentence: "7 years",
  },
  // Violent Crimes
  {
    id: "FG-2233",
    name: "Meera Reddy",
    age: 31,
    gender: "Female",
    city: "Hyderabad",
    occupation: "Software Engineer",
    employer: "InfoTech Systems",
    priorCount: 0,
    currentCrime: "Assault",
    maxSentence: "3 years",
  },
  {
    id: "GH-5566",
    name: "Rakesh Tiwari",
    age: 29,
    gender: "Male",
    city: "Lucknow",
    occupation: "Unemployed",
    priorCount: 2,
    currentCrime: "Aggravated Assault",
    maxSentence: "7 years",
  },
  {
    id: "HI-7788",
    name: "Sunita Devi",
    age: 45,
    gender: "Female",
    city: "Patna",
    occupation: "Agricultural Laborer",
    priorCount: 0,
    currentCrime: "Murder",
    maxSentence: "Life imprisonment",
  },
  {
    id: "IJ-9900",
    name: "Farhan Sheikh",
    age: 24,
    gender: "Male",
    city: "Mumbai",
    occupation: "Delivery Driver",
    employer: "QuickDeliver App",
    priorCount: 1,
    currentCrime: "Culpable Homicide",
    maxSentence: "10 years",
  },
  {
    id: "JK-1122",
    name: "Manoj Pandey",
    age: 50,
    gender: "Male",
    city: "Varanasi",
    occupation: "Priest/Tour Guide",
    priorCount: 1,
    currentCrime: "Assault & Robbery",
    caseAmount: "₹80,000",
    maxSentence: "10 years",
  },
  // DUI & Traffic Crimes
  {
    id: "KL-3344",
    name: "Arjun Malhotra",
    age: 26,
    gender: "Male",
    city: "Chandigarh",
    occupation: "Marketing Executive",
    employer: "AdWorld Media",
    priorCount: 1,
    currentCrime: "DUI with Injury",
    maxSentence: "10 years",
  },
  {
    id: "LM-5566",
    name: "Ravi Shankar",
    age: 35,
    gender: "Male",
    city: "Chennai",
    occupation: "Truck Driver",
    priorCount: 0,
    currentCrime: "Fatal Accident - Negligence",
    maxSentence: "10 years",
  },
  // Drugs & Contraband
  {
    id: "MN-7788",
    name: "Bunty alias Satish Kumar",
    age: 32,
    gender: "Male",
    city: "Delhi",
    occupation: "Unemployed",
    priorCount: 2,
    currentCrime: "Drug Trafficking",
    caseAmount: "₹4,00,000",
    maxSentence: "20 years",
  },
  {
    id: "NO-9900",
    name: "Pinky Sharma",
    age: 23,
    gender: "Female",
    city: "Goa",
    occupation: "Cafe Worker",
    employer: "Beach Shack",
    priorCount: 0,
    currentCrime: "Drug Peddling",
    maxSentence: "10 years",
  },
  // Domestic & Family
  {
    id: "OP-1122",
    name: "Suresh Gaikwad",
    age: 48,
    gender: "Male",
    city: "Kolhapur",
    occupation: "Factory Supervisor",
    employer: "Gokul Sugar Mills",
    priorCount: 1,
    currentCrime: "Domestic Violence & Stalking",
    maxSentence: "3 years",
  },
  {
    id: "PQ-3344",
    name: "Rekha Saxena",
    age: 52,
    gender: "Female",
    city: "Kanpur",
    occupation: "Homemaker",
    priorCount: 0,
    currentCrime: "Dowry Harassment",
    maxSentence: "10 years",
  },
  // Cyber & Fraud
  {
    id: "QR-5566",
    name: "Rohit Mehra",
    age: 27,
    gender: "Male",
    city: "Noida",
    occupation: "Freelance Developer",
    priorCount: 0,
    currentCrime: "Cyber Fraud / Phishing",
    caseAmount: "₹35,00,000",
    maxSentence: "7 years",
  },
  {
    id: "RS-7788",
    name: "Anjali Verma",
    age: 34,
    gender: "Female",
    city: "Bangalore",
    occupation: "HR Manager",
    employer: "TechStart Inc",
    priorCount: 0,
    currentCrime: "Identity Theft & Fraud",
    caseAmount: "₹28,00,000",
    maxSentence: "7 years",
  },
  {
    id: "ST-9900",
    name: "Mohammed Rizwan",
    age: 22,
    gender: "Male",
    city: "Hyderabad",
    occupation: "College Student",
    priorCount: 0,
    currentCrime: "Exam Paper Leak",
    maxSentence: "3 years",
  },
  {
    id: "UV-1122",
    name: "Deepak Sharma",
    age: 40,
    gender: "Male",
    city: "Ahmedabad",
    occupation: "Real Estate Agent",
    priorCount: 1,
    currentCrime: "Cheating & Forgery",
    caseAmount: "₹2,40,00,000",
    maxSentence: "7 years",
  },
  {
    id: "WX-3344",
    name: "Lakshmi Narayan",
    age: 62,
    gender: "Male",
    city: "Coimbatore",
    occupation: "Retired Bank Manager",
    priorCount: 0,
    currentCrime: "Money Laundering",
    caseAmount: "₹1,20,00,000",
    maxSentence: "17 years",
  },
];

// Get random suspect card
export function getRandomSuspectCard(): SuspectCardData {
  const index = Math.floor(Math.random() * suspectCards.length);
  return suspectCards[index];
}
